export const CREATE_TODO = 'CREATE_TODO';
export const UPDATE_TODO = 'UPDATE_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const CHANGE_TODO_FILTER = 'CHANGE_TODO_FILTER';
export const CLEAR_COMPLETED_TODO = 'CLEAR_COMPLETED_TODO';
